// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-hUL3xAsoMBsxfnTuKu37bhB674XBGtg',
    appId: '1:477161595016:web:6e6852debe2289d6037f3d',
    messagingSenderId: '477161595016',
    projectId: 'instagram-clone-v2-f323f',
    authDomain: 'instagram-clone-v2-f323f.firebaseapp.com',
    storageBucket: 'instagram-clone-v2-f323f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLsj-ytEnaZbK7xwwCdyp3OjAPAn0m_A',
    appId: '1:477161595016:android:2274a838cb6c1969037f3d',
    messagingSenderId: '477161595016',
    projectId: 'instagram-clone-v2-f323f',
    storageBucket: 'instagram-clone-v2-f323f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjaoQbkulvPBNxPnIMvELGLxTjzXr3c4',
    appId: '1:477161595016:ios:a557ba45f905a2f7037f3d',
    messagingSenderId: '477161595016',
    projectId: 'instagram-clone-v2-f323f',
    storageBucket: 'instagram-clone-v2-f323f.appspot.com',
    iosClientId: '477161595016-8g2vl8tae98irvr1acleu9q1lugkauts.apps.googleusercontent.com',
    iosBundleId: 'com.instagramclonev2.app',
  );
}
